name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: vinod900/mongodb:v1 # docker build -t vinod900/mongodb:v1
    container_name: mongodb # docker run -d --network roboshop vinod900/mongodb:v1
  catalogue:
    build: ./catalogue
    image: vinod900/catalogue.v1
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: vinod900/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
  user:
    build: ./user
    image: vinod900/user:v1
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - redis
    - mongodb
  redis:
    image: redis:7
    container_name: redis 
networks:
  default: # this means all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network
    
