name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:v1 # docker build -t joindevops/mongodb:v1
    container_name: mongodb # docker run -d --network roboshop joindevops/mongodb:v1
    volumes:
    - mongodb:/data/db # mongodb stores data in /data/db directory
  catalogue:
    build: ./catalogue
    image: joindevops/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
  user:
    build: ./user
    image: joindevops/user:v1
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - redis
    - mongodb
  cart:
    build: ./cart
    image: joindevops/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: joindevops/shipping:v1
    container_name: shipping
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: mysql
    depends_on:
    - mysql
    - cart
  payment:
    build: ./payment
    image: joindevops/payment:v1
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - cart
    - user
    - rabbitmq
  redis:
    image: redis:7
    container_name: redis # docker run -d --name redis --network roboshop redis:7
    volumes:
    - redis:/data
  mysql:
    image: joindevops/mysql:v1
    build: ./mysql
    container_name: mysql
    command: --mysql-native-password=ON --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
networks:
  default: # this means all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network
volumes:
  mongodb: # docker volume create mongodb
  redis: # docker volume create redis
  mysql: # docker volume create mysql
  rabbitmq: # docker volume create rabbitmq